### ISSUE TITLE
Problem INstalling 

### ISSUE THREAD

**Issue by gzero20** [Bachmann1234/java9_kernel#13]
Hi I can't succeed. please see screenshot below

![image](https://cloud.githubusercontent.com/assets/13022982/11452480/c3f291b2-9623-11e5-8389-b3b1aad9f046.png)

**Comment by dsblank** [comment]
How did you install ipython? This is one good way: `pip install ipython[notebook]`

If you want magics, you can also: `pip install metakernel`

**Comment by gzero20** [comment]
Using Anaconda

**Comment by gzero20** [comment]
My problem is I followed your tutorial but not sure on the environment part. Can you check? Do you have Skype? I badly need your help/

**Comment by dsblank** [comment]
You can use pip with anaconda. 

You can also try to install `pexpect` directly.

**Comment by gzero20** [comment]
yes i know but that's not where I stuck. Ive been using python for quite some time so the pip and all are okay but i don't know which part I;m missing here

**Comment by Bachmann1234** [comment]
Hmm, ill see if I can get this to work on anaconda. Ill see if I get some time tomorrow.

I dont know why it would be a problem, but if it works I can put some steps in here

**Comment by dsblank** [comment]
It could be that the python2 in your path is not the same as your Anaconda environment python2. If so, you should change the argv python2 to point to the real one. You can find it by running your Anaconda python2, and then:

``` python
import sys
print sys.executable
```

In fact, if we build a real installer, it would generate the kernel.json on the fly, and put that in argv.

**Comment by Bachmann1234** [comment]
Howdy!

So, I created a fresh user on my mac and installed anaconda to test this.

It was the 64-bit graphical installer, python 2, installed for the user only.

It worked for me.  My best guess for your issue is that @dsblank is right and that the kernel.son is pointing to the wrong python environment. 

Here is the kernel.json I used

```
{
 "argv": ["/Users/tempbach/anaconda/bin/python", "/Users/tempbach/java9_kernel/javakernel",
          "-f", "{connection_file}"],
 "display_name": "Java 9",
 "language": "java",
 "env" : {
     "JAVA_9_HOME": "/Library/Java/JavaVirtualMachines/jdk1.9.0.jdk/Contents/Home",
     "KULLA_HOME": "/Users/tempbach/Downloads/kulla.jar"
     }
 } 
```

The biggest difference would be the path for the python script.

I hope this helps.

**Comment by gzero20** [comment]
For the kulla.jar, no need to do anything right? I still can't have it
work. :(

**Comment by gzero20** [comment]
BTW, i'm already using Jupyter

**Comment by gzero20** [comment]
My OS is 10.11.1

**Comment by Bachmann1234** [comment]
@gmur24 I don't think so. As long as the jar is there you should be fine. 

Its hard for me to say much further without sitting with you. 

Ultimately what the error is telling you is that the modules you expect to be installed are not installed. Anaconda includes all these. So all I got to advise is to look really closely at that python command you have in your kernel.

What is the output of 
`which python2` ?

**Comment by Bachmann1234** [comment]
Anything else to do here? If I dont hear back ill go ahead and close this
