### ISSUE TITLE
Use MetaKernel to provide Magics and shell

### ISSUE THREAD

**Issue by dsblank** [Bachmann1234/java9_kernel#3]
With just a couple of line changes, you can have magics and shell commands. 

Would you like a PR to use MetaKernel?

https://github.com/Calysto/metakernel/tree/master/metakernel

**Comment by Bachmann1234** [comment]
So im not completely closed off to the idea I just have not had the time to dig into it very deeply to understand what that would mean exactly.

My browsing of the metakernel docs make a lot of references to "magics" but I don't quite get what that means. From the examples it seems to be cool shortcuts for various visualizations and tools. 

I'm especially unsure what this means in the java case.

**Comment by dsblank** [comment]
It is pretty simple, but the name is very misleading, and the ipython use is slightly different. Magics are metacommands... a language of sorts that sits on top of the kernel. In ipython, magics are interspersed with the Python language. But metakernel is language agnostic, and so there is a clear boundary between language and magics.

Here is a sample notebook using the Java9 (with some additions) and magics:

https://athena.brynmawr.edu/jupyter/hub/dblank/public//Experiments/Java9.ipynb

**Comment by Bachmann1234** [comment]
Hmm, alrighty, make the PR and ill review. Ill probably merge but I do wanna play with it a bit

**Comment by dsblank** [comment]
Would you prefer that the use of metakernel be optional? If so, then a couple of wrapper methods will have to be created to allow both uses (with metakernel and without) to work. 

Alternatively, I can fork your repo and make it a full metakernel citizen and maintain it over at Calysto.Your choice!

**Comment by Bachmann1234** [comment]
Absolutely optional. We can update the readme to tell people how to enable it but the basic functionality should have as few dependencies as possible.

**Comment by dsblank** [comment]
Made a PR request #7

**Comment by dsblank** [comment]
Merged as 5454f1bbe
